 # Hadamardova transformacija
 
 Hademardova transformacija (Hadamard transform, Walsh–Hadamard transform, Hadamard–Rademacher–Walsh transform, Walsh transform, Walsh–Fourier transform) je primer klase koja generalizuje Furijeovu transformaciju.
 Ukratko, ona izvodi ortogonalnu, simetričnu, involutivnu, linearnu operaciju nad 2^m realnih brojeva (ili kompleksnih).
 
 Hadamardova transformacija se može smatrati izgrađenom od diskretnih Furijeovih transformacija (DFT) veličine 2 i zapravo je ekvivalentna višedimenzionalnom DFT-u veličine 2 × 2 × ⋯ × 2 × 2.

Matrica Hademardove transformacije se dobija rekurentnom relacijom:

$$H_0 = + (1)$$

$$H_m = \frac{1}{\sqrt{2}} \begin{pmatrix}H_{m-1} & H_{m-1}\\
H_{m-1} & -H_{m-1}
\end{pmatrix}$$

Kako izgledaju matrice za m = 1, 2, 3.

$$H_1 = \frac{1}{\sqrt{2}} \begin{pmatrix}1 & 1\\
1 & -1
\end{pmatrix}$$

$$H_2 = \frac{1}{2} \begin{pmatrix}1 & 1 & 1 & 1\\
1 & -1 & 1 & -1\\
1 & 1 & -1 & -1\\
1 & -1 & -1 & 1\\
\end{pmatrix}$$

$$H_3 = \frac{1}{2^{3/2}} \begin{pmatrix}1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & -1 & 1 & -1 & 1 & -1 & 1 & -1\\
1 & 1 & -1 & -1 & 1 & 1 & -1 & -1\\
1 & -1 & -1 & 1 & 1 & -1 & -1 & 1\\
1 & 1 & 1 & 1 & -1 & -1 & -1 & -1\\
1 & -1 & 1 & -1 & -1 & 1 & -1 & 1\\
1 & 1 & -1 & -1 & -1 & -1 & 1 & 1\\
1 & -1 & -1 & 1 & -1 & 1 & -1 & 1\\
\end{pmatrix}$$

Ekvivalentno, Hadamardovu tranformaciju možemo definisati i pokoordinatno:

\begin{aligned}k&=\sum _{i=0}^{m-1}{k_{i}2^{i}}=k_{m-1}2^{m-1}+k_{m-2}2^{m-2}+\dots +k_{1}2+k_{0}\\n&=\sum _{i=0}^{m-1}{n_{i}2^{i}}=n_{m-1}2^{m-1}+n_{m-2}2^{m-2}+\dots +n_{1}2+n_{0}\end{aligned}
gde su kj i nj elementi 0 ili 1 od k i n, redom. 
Za element u gornjem levom uglu definišemo: k=n=0. I u ovom slucaju imamo:
{\displaystyle (H_{m})_{k,n}={\frac {1}{2^{m/2}}}(-1)^{\sum _{j}k_{j}n_{j}}}{\displaystyle (H_{m})_{k,n}={\frac {1}{2^{m/2}}}(-1)^{\sum _{j}k_{j}n_{j}}}

In [1]:
import numpy as np

In [2]:
def hademard_matrix(n):
    h_0 = 1
    
    h_prev = h_0
    c = 1
    for _ in range(n):
        h_new = np.block([[h_prev, h_prev], [h_prev, -1 * h_prev]])
        
        c *= 1 / np.sqrt(2)
        h_prev = h_new
        
    return h_new, c

In [3]:
n = 3

In [4]:
m, c = hademard_matrix(n)

In [5]:
c 

0.3535533905932737

In [6]:
m

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1,  1,  1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1,  1],
       [ 1,  1,  1,  1, -1, -1, -1, -1],
       [ 1, -1,  1, -1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1, -1,  1,  1],
       [ 1, -1, -1,  1, -1,  1,  1, -1]])

#### Preuredjena Hadamardova transformacija - Walshova transformacija

In [7]:
def walsh_order(n):
    m, c = hademard_matrix(n)
    
    N = m.shape[0]
    array = np.zeros(N)
    
    for i in range(N):
        row = m[i]
        count = 0
        
        for j in range(N - 1):
            if row[j] * row[j + 1] == -1:
                count += 1
        array[i] = count
            
    a = []
    for i in range(N):
        arg_max = np.argmin(array)
        
        a.append(m[arg_max])
        array[arg_max] = N
        
    return a

In [8]:
a = walsh_order(n)

In [9]:
a

[array([1, 1, 1, 1, 1, 1, 1, 1]),
 array([ 1,  1,  1,  1, -1, -1, -1, -1]),
 array([ 1,  1, -1, -1, -1, -1,  1,  1]),
 array([ 1,  1, -1, -1,  1,  1, -1, -1]),
 array([ 1, -1, -1,  1,  1, -1, -1,  1]),
 array([ 1, -1, -1,  1, -1,  1,  1, -1]),
 array([ 1, -1,  1, -1, -1,  1, -1,  1]),
 array([ 1, -1,  1, -1,  1, -1,  1, -1])]

#### 1D Primer

#### 2D Primer