 # Hadamardova transformacija
 
 Hademardova transformacija (Hadamard transform, Walsh–Hadamard transform, Hadamard–Rademacher–Walsh transform, Walsh transform, Walsh–Fourier transform) je primer klase koja generalizuje Furijeovu transformaciju.
 Ona izvodi ortogonalnu, simetričnu, involutivnu, linearnu operaciju nad $2^{m}$ realnih (kompleksnih) brojeva.
 
 Hadamardova transformacija se može smatrati izgrađenom od diskretnih Furijeovih transformacija (DFT) veličine 2 i zapravo je ekvivalentna višedimenzionalnom DFT-u veličine 2 × 2 × ⋯ × 2 × 2.
 
 Matrica Hademardove transformacije se dobija rekurentnom relacijom:

$$H_0 = + (1)$$

$$H_m = \frac{1}{\sqrt{2}} \begin{pmatrix}H_{m-1} & H_{m-1}\\
H_{m-1} & -H_{m-1}
\end{pmatrix}$$

Hademardove matrice za m = 1, 2, 3.

$$H_1 = \frac{1}{\sqrt{2}} \begin{pmatrix}1 & 1\\
1 & -1
\end{pmatrix}$$

$$H_2 = \frac{1}{2} \begin{pmatrix}1 & 1 & 1 & 1\\
1 & -1 & 1 & -1\\
1 & 1 & -1 & -1\\
1 & -1 & -1 & 1\\
\end{pmatrix}$$

$$H_3 = \frac{1}{2^{3/2}} \begin{pmatrix}1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & -1 & 1 & -1 & 1 & -1 & 1 & -1\\
1 & 1 & -1 & -1 & 1 & 1 & -1 & -1\\
1 & -1 & -1 & 1 & 1 & -1 & -1 & 1\\
1 & 1 & 1 & 1 & -1 & -1 & -1 & -1\\
1 & -1 & 1 & -1 & -1 & 1 & -1 & 1\\
1 & 1 & -1 & -1 & -1 & -1 & 1 & 1\\
1 & -1 & -1 & 1 & -1 & 1 & -1 & 1\\
\end{pmatrix}$$


The Hadamard transform is also used in data encryption, as well as many signal processing and data compression algorithms, such as JPEG XR and MPEG-4 AVC. In video compression applications, it is usually used in the form of the sum of absolute transformed differences. It is also a crucial part of significant number of algorithms in quantum computing. The Hadamard transform is also applied in experimental techniques such as NMR, mass spectrometry and crystallography. It is additionally used in some versions of locality-sensitive hashing, to obtain pseudo-random matrix rotations.

In [1]:
import numpy as np

In [2]:
def hademard_matrix(n):
    h_0 = 1
    
    h_prev = h_0
    c = 1
    for _ in range(n):
        h_new = np.block([[h_prev, h_prev], [h_prev, -1 * h_prev]])
        
        c *= 1 / np.sqrt(2)
        h_prev = h_new
        
    return h_new, c

In [3]:
n = 3

In [4]:
m, c = hademard_matrix(n)

In [5]:
c 

0.3535533905932737

In [6]:
m

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1,  1,  1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1,  1],
       [ 1,  1,  1,  1, -1, -1, -1, -1],
       [ 1, -1,  1, -1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1, -1,  1,  1],
       [ 1, -1, -1,  1, -1,  1,  1, -1]])

Ekvivalentno, Hadamardovu tranformaciju možemo definisati i pokoordinatno za $(Hm)_{kn}$:

\begin{aligned}k&=\sum _{i=0}^{m-1}{k_{i}2^{i}}=k_{m-1}2^{m-1}+k_{m-2}2^{m-2}+\dots +k_{1}2+k_{0}\\n&=\sum _{i=0}^{m-1}{n_{i}2^{i}}=n_{m-1}2^{m-1}+n_{m-2}2^{m-2}+\dots +n_{1}2+n_{0}\end{aligned}
gde su $k_j$ i $n_j$ bitovi (0 ili 1) binarnog zapisa brojeva $k$ i $n$.  
Dobijamo:
$$(H_{m})_{k,n}={\frac {1}{2^{m/2}}}(-1)^{\sum _{j}k_{j}n_{j}}$$

Ovo je multidimenzionalna $2\times 2\times \cdots \times 2\times 2$ DFT, normalizovana da bude unitarna.

Na primer, ako je $m \geq 2$, tada je $$(H_{m})_{3,2}\;=\;(-1)^{3\cdot 2}\;=\;(-1)^{(1,1)\cdot (1,0)}\;=\;(-1)^{1+0}\;=\;(-1)^{1}\;=\;-1 $$

#### Preuredjena Hadamardova transformacija - Walshova transformacija

Redovi Hadamardove matrice su Walsh-ove funkcije.

In [11]:
def walsh_order(n):
    m, c = hademard_matrix(n)
    
    N = m.shape[0]
    array = np.zeros(N)
    
    for i in range(N):
        row = m[i]
        count = 0
        
        for j in range(N - 1):
            if row[j] * row[j + 1] == -1:
                count += 1
        array[i] = count
            
    a = []
    for i in range(N):
        arg_max = np.argmin(array)
        
        a.append(m[arg_max])
        array[arg_max] = N
        
    return a

In [12]:
a = walsh_order(n)

In [13]:
a

[array([1, 1, 1, 1, 1, 1, 1, 1]),
 array([ 1,  1,  1,  1, -1, -1, -1, -1]),
 array([ 1,  1, -1, -1, -1, -1,  1,  1]),
 array([ 1,  1, -1, -1,  1,  1, -1, -1]),
 array([ 1, -1, -1,  1,  1, -1, -1,  1]),
 array([ 1, -1, -1,  1, -1,  1,  1, -1]),
 array([ 1, -1,  1, -1, -1,  1, -1,  1]),
 array([ 1, -1,  1, -1,  1, -1,  1, -1])]

#### 1D Primer

#### 2D Primer

https://www.mathworks.com/help/signal/ug/discrete-walsh-hadamard-transform.html

https://www.mathworks.com/help/signal/ug/walshhadamard-transform.html

The Hadamard transform is also used in data encryption, as well as many signal processing and data compression algorithms, such as JPEG XR and MPEG-4 AVC. In video compression applications, it is usually used in the form of the sum of absolute transformed differences. It is also a crucial part of significant number of algorithms in quantum computing. The Hadamard transform is also applied in experimental techniques such as NMR, mass spectrometry and crystallography. It is additionally used in some versions of locality-sensitive hashing, to obtain pseudo-random matrix rotations.